// react-fronend/src/component/common/Navbar.jsx
import React from "react";
import { useNavigate, NavLink } from "react-router-dom";
import ApiService from "../../service/ApiService";



function Navbar() {
    const isAuthenticated = ApiService.isAthenticated();
    const isCustomer = ApiService.isCustomer();
    const isAdmin = ApiService.isAdmin();

    const navigate = useNavigate();

    const handleLogout = () => {
        const isLogout = window.confirm("Are you sure you want to logout?")
        if (isLogout) {
            ApiService.logout();
            navigate("/home");
        }
    }

    return(
        <nav className="navbar">
            <div className="navbar-brand">
                <NavLink to="/home"> Phegon Hotel </NavLink>
            </div>

            <ul className="navbar-ul">
                <li><NavLink to={"/home"} activeClassname="active">Home</NavLink></li>
                <li><NavLink to={"/rooms"} activeClassname="active">Rooms</NavLink></li>
                <li><NavLink to={"/find-booking"} activeClassname="active">Find My Bookings</NavLink></li>

                { isCustomer && <li><NavLink to={"/profile"} activeClassname="active">Profile</NavLink></li>}
                {isAdmin && <li><NavLink to={"/admin"} activeClassname="active">Admin</NavLink></li>}

                {!isAuthenticated && <li><NavLink to={"/login"} activeClassname="active">Login</NavLink></li>}
                {!isAuthenticated && <li><NavLink to={"/register"} activeClassname="active">Register</NavLink></li>}

                {isAuthenticated && <li onClick={handleLogout}>Logout</li>}
            </ul>
        </nav>
    )
}

export default Navbar;

// angular-frontend/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../service/api.service';
import { CommonModule } from '@angular/common';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';


@Component({
  selector: 'app-navbar',
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {

  constructor(private router: Router, private apiService: ApiService){}

  get isAuthemticated():boolean{
    return this.apiService.isAuthenticated();
  }

  get isCustomer():boolean{
    return this.apiService.isCustomer();
  }

  get isAdmin():boolean{
    return this.apiService.isAdmin();
  }

  handleLogout(): void{
    const isLogout = window.confirm("Are you sure you want to logout? ")
    if (isLogout) {
      this.apiService.logout();
      this.router.navigate(['/home'])
    }
  }

}

<nav>
    <div class="brand">
        <a href="/home">Phegon Hotel</a>
    </div>
    <ul>
        <li><a routerLink="/home" routerLinkActive="active">Home</a></li>
        <li><a routerLink="/rooms" routerLinkActive="active">Rooms</a></li>
        <li><a routerLink="/find-booking" routerLinkActive="active">Find Booking</a></li>


        <li *ngIf="isCustomer"><a routerLink="/profile" routerLinkActive="active">Profile</a></li>
        <li *ngIf="isAdmin"><a routerLink="/admin" routerLinkActive="active">Admin</a></li>
        <li *ngIf="!isAuthemticated"><a routerLink="/login" routerLinkActive="active">Login</a></li>
        <li *ngIf="!isAuthemticated"><a routerLink="/register" routerLinkActive="active">Register</a></li>

        <li *ngIf="isAuthemticated" (click)="handleLogout()">Logout</li>
    </ul>
</nav>
